// File: app/tarotCards.js
// This is a shared file containing all tarot card data for reuse in components

export const tarotCards = [
  {
    "name": "The Fool",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/0.jpg",
    "meaning": "Embark on a transformative journey of self-discovery and unlimited potential. The Fool invites you to step into the unknown with childlike wonder and unbridled courage. This card speaks to those standing at the precipice of a major life change, urging you to trust your instincts and embrace spontaneity. Whether you're considering a career shift, starting a new relationship, or pursuing a long-held dream, now is the time to leap forward with an open heart and mind. Your innocence and optimism are your greatest strengths—don't let fear of the unknown hold you back. The universe is conspiring in your favor, offering support and guidance as you take this bold first step.",
    "reversedMeaning": "Caution has transformed into paralysis, and fear is preventing you from moving forward. The reversed Fool warns of analysis paralysis, overthinking, and missed opportunities. You may be so caught up in potential risks that you've become stuck, unable to take meaningful action. This is a moment of self-reflection—are your carefully constructed plans actually protecting you, or are they walls that imprison your potential? Break free from self-imposed limitations. Recognize that perfect planning is an illusion, and true growth happens when you're willing to take calculated risks. Examine what's truly holding you back—is it genuine concern or simply fear disguised as wisdom?",
  },
  {
    "name": "The Magician",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/1.jpg",
    "meaning": "You stand at the powerful intersection of skill, opportunity, and manifestation. The Magician reveals that you possess all the tools necessary to create profound change in your life. This is a moment of extraordinary potential—your creativity, intelligence, and personal power are aligned to bring your deepest desires into reality. Whether it's a professional goal, personal project, or spiritual aspiration, you have the unique ability to transform vision into concrete achievement. Pay attention to your intentions and focus. Every resource you need is already within your grasp. Trust in your abilities, be strategic in your approach, and watch as the universe conspires to support your most ambitious dreams.",
    "reversedMeaning": "Potential is slipping through your fingers like sand. The reversed Magician exposes inner conflicts, scattered energy, and self-doubt that are preventing you from leveraging your true capabilities. You might be experiencing a profound disconnect between your skills and your execution—perhaps doubting yourself, misusing your talents, or allowing external negativity to cloud your judgment. This is a critical moment to realign your inner dialogue. Are you sabotaging your own success through procrastination, self-criticism, or fear of visibility? Reclaim your power by acknowledging your unique gifts and committing to intentional, focused action.",
  },
  {
    "name": "The High Priestess",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/2.jpg",
    "meaning": "You are being called to dive deep into the realm of intuition, inner wisdom, and hidden knowledge. The High Priestess represents a profound spiritual awakening and a connection to your subconscious mind. This is a time of introspection, where logic gives way to intuitive understanding. Trust the whispers of your inner voice—those seemingly inexplicable feelings and subtle insights are guiding you towards a deeper truth. Meditate, journal, and create space for quiet reflection. Important revelations are emerging, offering guidance that transcends rational thought. Your intuition is a powerful compass, capable of navigating complex emotional and spiritual landscapes.",
    "reversedMeaning": "The veil of illusion has thickened, creating confusion and disconnection from your inner wisdom. The reversed High Priestess suggests you're struggling to trust your intuition, perhaps drowning in external noise or suppressing your authentic inner voice. You might be experiencing intense emotional or psychological barriers that prevent clear insight. This is a call to reconnect with yourself—to cut through external expectations and societal conditioning. Healing requires creating intentional silence, confronting uncomfortable truths, and courageously listening to the wisdom that resides beneath surface-level understanding."
  },
  {
    "name": "The Empress",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/3.jpg",
    "meaning": "You are being called to dive deep into the realm of intuition, inner wisdom, and hidden knowledge. The High Priestess represents a profound spiritual awakening and a connection to your subconscious mind. This is a time of introspection, where logic gives way to intuitive understanding. Trust the whispers of your inner voice—those seemingly inexplicable feelings and subtle insights are guiding you towards a deeper truth. Meditate, journal, and create space for quiet reflection. Important revelations are emerging, offering guidance that transcends rational thought. Your intuition is a powerful compass, capable of navigating complex emotional and spiritual landscapes.",
    "reversedMeaning": "The veil of illusion has thickened, creating confusion and disconnection from your inner wisdom. The reversed High Priestess suggests you're struggling to trust your intuition, perhaps drowning in external noise or suppressing your authentic inner voice. You might be experiencing intense emotional or psychological barriers that prevent clear insight. This is a call to reconnect with yourself—to cut through external expectations and societal conditioning. Healing requires creating intentional silence, confronting uncomfortable truths, and courageously listening to the wisdom that resides beneath surface-level understanding."
  },
  {
    "name": "The Emperor",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/4.jpg",
    "meaning": "Abundance, creativity, and nurturing energy are blossoming in your life. The Empress invites you to embrace your inherent power of creation and self-love. This is a profound moment of fertility—not just in a literal sense, but in the richness of your personal and professional endeavors. You are being called to honor your creative impulses, to nurture your dreams with the same tenderness you would offer a beloved child. Whether it's a project, relationship, or personal growth journey, you have the capacity to bring forth something beautiful and meaningful. Connect with your body, your emotions, and the natural rhythms of life. Trust in your ability to create, to heal, and to manifest abundance in all its forms.",
    "reversedMeaning": "Creative blockages and emotional burnout have taken their toll. The reversed Empress reveals a struggle with self-care, over-giving, or feeling emotionally depleted. You may be experiencing a disconnect from your nurturing energy—giving too much to others while neglecting your own needs. This is a critical moment of recalibration. Are you sacrificing your own well-being in the name of productivity or caretaking? Healing requires setting firm boundaries, reconnecting with your inner source of creativity, and learning to receive as much as you give. Rediscover the art of self-compassion and allow yourself the same level of care you so generously offer to others.",
  },
  {
    "name": "The Lovers",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/6.jpg",
    "meaning": "A profound crossroads of connection, choice, and personal alignment awaits you. The Lovers card transcends simple romantic interpretations, speaking to the deeper harmony between your inner and outer worlds. You are being called to make a choice that resonates with your most authentic self—a decision that aligns your heart, mind, and spirit. This might involve a relationship, a career path, or a personal commitment that requires you to honor your true values. Pay attention to the subtle energies of attraction and repulsion. What truly lights you up? What connections feel genuinely supportive of your growth? This is a moment of sacred choice, where integrity and passion intersect.",
    "reversedMeaning": "Internal conflict and misalignment are creating emotional turbulence. The reversed Lovers card reveals deep-seated challenges in maintaining healthy connections—with others and with yourself. You may be experiencing a painful disconnect, where external relationships or personal choices feel out of sync with your authentic self. Fear, compromise, and unhealed patterns are creating disharmony. This is a critical moment of soul-searching. Are you choosing from a place of genuine love and respect, or from a place of fear and old conditioning? Healing requires brutal honesty, the courage to release relationships or situations that no longer serve your highest good, and the commitment to realign with your true essence.",
  },
  {
    "name": "The Chariot",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/7.jpg",
    "meaning": "Triumph, willpower, and focused determination are propelling you forward. The Chariot represents a powerful moment of personal victory, where your inner resolve meets external opportunity. You are being called to harness your diverse energies, reconcile internal conflicts, and move decisively towards your goals. This is not just about winning, but about mastering the art of conscious direction. Whether you're navigating a professional challenge, personal transformation, or spiritual journey, you have the strength to overcome obstacles and chart a clear course. Control your inner dialogue, maintain unwavering focus, and trust in your ability to navigate even the most challenging terrains.",
    "reversedMeaning": "Fragmented energy and lack of direction are creating substantial roadblocks. The reversed Chariot exposes internal conflicts that are preventing forward movement. You may feel pulled in multiple directions, struggling with indecision, or experiencing a profound sense of being stuck. Underlying fears, unresolved emotional patterns, or a lack of clear vision are sabotaging your progress. This is a moment of radical recalibration. Are you allowing external pressures or internal doubts to derail your momentum? Reclaim your power by getting brutally honest about what truly matters. Realign your actions with your deepest intentions, and remember that true victory comes from inner harmony.",
  },
  {
    "name": "The Hermit",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/9.jpg",
    "meaning": "A sacred period of introspection and spiritual retreat is calling you. The Hermit represents a profound journey inward, where external noise fades and inner wisdom takes center stage. You are being guided to step away from the world's distractions and connect with your deepest self. This is not about isolation, but about cultivating profound self-understanding and spiritual clarity. Whether you're seeking answers to life's complex questions, healing from past experiences, or preparing for a significant transformation, solitude is your greatest teacher. Embrace this time of reflection—meditate, journal, explore your inner landscape. Illumination comes not from external sources, but from the quiet wisdom within.",
    "reversedMeaning": "Spiritual stagnation and disconnection are threatening your inner growth. The reversed Hermit suggests you're either too withdrawn or struggling to integrate your insights. You may be using isolation as a defense mechanism, avoiding necessary interactions and emotional processing. Alternatively, you might be resisting the call to look inward, filling your life with noise to avoid confronting deeper truths. This is a moment of radical honesty. Are you using solitude as a shield or a tool for genuine self-discovery? Break through the barriers of fear and reconnect with your authentic self, allowing vulnerability and introspection to guide your path.",
  },
  {
    "name": "Wheel of Fortune",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/10.jpg",
    "meaning": "The cosmic dance of destiny is unfolding before you. The Wheel of Fortune represents a profound moment of universal alignment, where seemingly random events weave into a meaningful tapestry of experience. You are standing at a pivotal point of transformation, where past actions, present choices, and future possibilities converge. This is not about passive acceptance, but active participation in life's grand cycle. Embrace the understanding that change is the only constant—what appears as chaos is actually a sophisticated rhythm of growth and renewal. Trust that every twist of fate carries a deeper lesson, every challenge a hidden opportunity. Your resilience, adaptability, and faith will be your greatest allies in navigating this dynamic journey.",
    "reversedMeaning": "Resistance to life's natural flow is creating internal and external turbulence. The reversed Wheel of Fortune reveals a struggle against inevitable change, where fear and attachment are blocking your path to growth. You may be experiencing a sense of powerlessness, feeling like a victim of circumstances rather than an active participant in your destiny. This is a critical moment of surrender—not to defeat, but to the wisdom of life's unpredictable nature. Are you clinging to outdated patterns, resisting the very changes that could liberate you? Healing requires releasing control, trusting the larger pattern, and finding peace within uncertainty.",
  },
  {
    "name": "The Sun",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/19.jpg",
    "meaning": "A radiant wave of joy, success, and pure potential is illuminating your path. The Sun represents a moment of absolute clarity, where your inner light shines brightest and external circumstances align with your deepest aspirations. This is more than temporary happiness—it's a profound state of alignment where your authentic self merges with life's abundant possibilities. Every challenge you've navigated has prepared you for this moment of triumph. Celebrate your journey, embrace your unique brilliance, and allow your natural enthusiasm to inspire both yourself and others. Your confidence is not arrogance, but a pure expression of your intrinsic worth and creative power.",
    "reversedMeaning": "Hidden shadows are temporarily obscuring your inner light. The reversed Sun suggests you're struggling with self-doubt, experiencing a disconnect between your potential and your current perception. Negative thought patterns, past traumas, or external criticisms might be dimming your natural radiance. This is not a permanent state, but a call to reclaim your power. Are you allowing temporary setbacks to define your entire narrative? Healing requires gentle self-compassion, reconnecting with your core strengths, and remembering that your worth is not determined by external validation. Your light is always present, even when clouds momentarily block its brilliance.",
  },
  {
    "name": "Justice",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/11.jpg",
    "meaning": "A profound moment of cosmic equilibrium and personal accountability is unfolding. Justice represents the delicate balance between action and consequence, inviting you to examine your life with absolute clarity and integrity. This is not about external judgment, but a deep internal reckoning where you align your actions with your highest principles. Every choice you've made has led you to this moment of profound truth-telling. You are being called to look beyond surface-level narratives, to understand the intricate web of cause and effect that shapes your reality. Embrace radical honesty, take responsibility for your path, and trust that true fairness emerges from authentic self-reflection.",
    "reversedMeaning": "Distorted perceptions and unresolved internal conflicts are disrupting your sense of balance. The reversed Justice card reveals areas where you might be avoiding accountability, rationalizing past actions, or perpetuating cycles of self-deception. You may be experiencing a profound misalignment between your actions and your values, creating internal tension and external complications. This is a critical moment of truth-seeking. Are you willing to look beyond convenient narratives and confront the deeper patterns that no longer serve you? Healing requires courageous self-examination, the willingness to make amends, and the commitment to realign with your most authentic self."
  },
  {
    "name": "The Hanged Man",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/12.jpg",
    "meaning": "A sacred pause in your journey invites profound transformation through surrender and radical perspective shift. The Hanged Man represents a mystical moment of suspension, where traditional approaches dissolve and a deeper wisdom emerges. This is not about passive waiting, but active surrender—releasing control to discover a more expansive understanding of your path. You are being called to view your challenges from an entirely new angle, to let go of rigid thinking and embrace the beauty of not-knowing. Suspend your usual strategies, allow vulnerability to be your teacher, and trust that enlightenment often comes through stillness, not constant action.",
    "reversedMeaning": "Resistance to necessary transformation is creating internal stagnation. The reversed Hanged Man reveals a struggle with surrender, where fear of change and attachment to old narratives are blocking your growth. You may be experiencing a sense of being stuck, oscillating between indecision and forced movement. This is a critical moment of honest reflection. Are you genuinely processing your experiences, or merely spinning in mental loops? Healing requires the courage to release control, to sit with uncertainty, and to trust that profound insights emerge when you stop forcing outcomes.",
  },
  {
    "name": "Death",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/13.jpg",
    "meaning": "A powerful metamorphosis is calling you to release what no longer serves your highest evolution. Death represents not an ending, but a profound transition—a sacred shedding of old skin to reveal your most authentic self. This is a moment of radical transformation where outdated patterns, relationships, beliefs, and identities are dissolving to make space for unprecedented growth. Do not fear this process; you are being lovingly dismantled so that your truest essence can emerge. Embrace the dissolution, trust the unknown, and know that every ending carries the seeds of a more aligned, powerful beginning.",
    "reversedMeaning": "Resistance to necessary change is creating internal and external blockages. The reversed Death card reveals a profound struggle with transformation, where fear of letting go is preventing your natural evolution. You may be clinging to familiar pain, outdated structures, or incomplete versions of yourself out of a misguided sense of safety. This is a critical moment of honest confrontation. Are you truly living, or merely existing within comfortable limitations? Healing requires the courage to acknowledge what needs to be released, to grieve the passing of old narratives, and to trust the regenerative power of surrender."
  },
  {
    "name": "The Hierophant",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/5.jpg",
    "meaning": "Tradition, spiritual wisdom, and structured belief systems are guiding your path. The Hierophant represents a connection to established institutions, rituals, and conventional wisdom. This card invites you to seek guidance from mentors, teachers, or spiritual leaders who can help you navigate your journey. It’s a time to honor tradition while also finding your place within it. Whether you’re exploring a new spiritual path, seeking education, or looking for structure in your life, the Hierophant encourages you to find meaning in shared beliefs and practices.",
    "reversedMeaning": "Rebellion against tradition, unconventional paths, and questioning established norms. The reversed Hierophant suggests you may be feeling constrained by societal expectations or rigid belief systems. This is a time to break free from dogma and explore your own unique spiritual path. Are you blindly following tradition, or are you seeking a deeper, more personal connection to your beliefs? Healing requires finding a balance between respecting tradition and honoring your individuality."
  },
  {
    "name": "Temperance",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/14.jpg",
    "meaning": "You are being guided to find harmony and balance in all aspects of your life. Temperance represents the art of blending opposites, creating a seamless flow between different energies. This card encourages you to practice patience, moderation, and self-control. Whether you're juggling work and personal life, managing conflicting emotions, or seeking spiritual alignment, Temperance reminds you that true fulfillment comes from finding the middle path. Trust in the process of integration and allow yourself to move at a steady, purposeful pace.",
    "reversedMeaning": "Imbalance and excess are disrupting your equilibrium. The reversed Temperance card suggests you may be struggling with extremes—overindulgence, impatience, or a lack of direction. You might feel pulled in different directions, unable to find a sense of stability. This is a moment to reassess your priorities and to seek a more balanced approach. Are you rushing towards a goal without considering the consequences? Healing requires slowing down, practicing self-discipline, and finding a harmonious rhythm in your life."
  },
  {
    "name": "The Devil",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/15.jpg",
    "meaning": "You are being confronted with your shadow self, the parts of you that are often hidden or repressed. The Devil represents the chains of attachment, addiction, and limiting beliefs that hold you back from true freedom. This card invites you to examine the areas of your life where you feel trapped or controlled by external forces. It's a call to confront your fears, to break free from self-imposed limitations, and to reclaim your power. Recognize that the chains you wear are often of your own making, and that liberation comes from within.",
    "reversedMeaning": "A powerful transformation is underway as you begin to release the bonds that have held you captive. The reversed Devil card suggests you are breaking free from unhealthy patterns, addictions, or toxic relationships. This is a moment of liberation, where you reclaim your autonomy and step into your true power. Are you ready to let go of what no longer serves you? Healing requires courage, self-awareness, and a willingness to face the darker aspects of yourself in order to emerge stronger and more empowered."
  },
  {
    "name": "The Tower",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/16.jpg",
    "meaning": "A sudden and dramatic upheaval is shaking the foundations of your life. The Tower represents a moment of revelation, where old structures and beliefs are torn down to make way for new growth. This card often signifies a crisis or a shocking event that forces you to confront the truth. While the experience may be unsettling, it is ultimately a necessary step towards transformation. Embrace the chaos, for it is through destruction that you will find clarity and a renewed sense of purpose.",
    "reversedMeaning": "Resistance to change is prolonging the inevitable. The reversed Tower suggests you may be trying to avoid a necessary upheaval, clinging to outdated structures or beliefs out of fear. This is a moment to confront the truth and to recognize that avoiding change will only lead to greater turmoil in the long run. Are you holding onto something that needs to be released? Healing requires embracing the uncertainty and trusting that the destruction of the old will pave the way for the new."
  },
  {
    "name": "The Star",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/17.jpg",
    "meaning": "Hope, inspiration, and spiritual renewal are shining brightly in your life. The Star represents a beacon of light after a period of darkness, offering guidance and reassurance. This card encourages you to have faith in the future and to trust that the universe is supporting your journey. It’s a time to dream big, to reconnect with your inner aspirations, and to believe in the power of your own potential. The Star reminds you that even in the darkest times, there is always a glimmer of hope.",
    "reversedMeaning": "Lack of faith, despair, and a sense of hopelessness are clouding your vision. The reversed Star suggests you may be struggling to see the light at the end of the tunnel. This is a moment to reconnect with your inner hope and to trust that brighter days are ahead. Are you allowing fear or doubt to overshadow your dreams? Healing requires rekindling your faith in the universe and in yourself."
  },
  {
    "name": "Strength",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/8.jpg",
    "meaning": "A profound awakening of inner courage and compassionate power is emerging. Strength is not about domination or external force, but about mastering your inner landscape with grace and wisdom. You are being called to integrate your passionate, instinctual self with your higher consciousness. This moment requires you to face challenges not with aggression, but with calm, centered presence. Imagine a gentle hand taming a wild lion—this is the essence of true strength. It's about transforming raw, potentially destructive energy into a powerful force of healing and transformation. Your most significant battles are won through self-understanding, emotional intelligence, and the courage to remain vulnerable. Whether you're confronting personal fears, navigating complex relationships, or overcoming internal barriers, your power lies in your ability to approach life with both fierce compassion and tender understanding.",
    "reversedMeaning": "Internal chaos and emotional turbulence are threatening your equilibrium. The reversed Strength card reveals a profound struggle with self-control, where primal emotions and unhealed wounds are overwhelming your rational mind. You may be experiencing intense inner conflicts—oscillating between feeling completely powerless and erupting with uncontrolled emotional intensity. This is a critical moment of emotional recalibration. Are you suppressing your true feelings out of fear, or allowing them to control you completely? Your current challenge is to develop a nuanced relationship with your emotions. True strength emerges not from denying your wild, passionate nature, but from learning to sit with uncomfortable feelings, to understand their origins, and to channel them with wisdom and self-compassion. This is a time to practice radical self-acceptance, to recognize that your so-called 'weaknesses' are actually portals to your greatest resilience."
  },
  {
    "name": "The Moon",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/18.jpg",
    "meaning": "Intuition, the unconscious mind, and hidden truths are coming to the surface. The Moon represents a time of deep introspection, where your dreams, fears, and subconscious thoughts are influencing your reality. This card encourages you to trust your instincts and to explore the mysteries of your inner world. It’s a time to pay attention to your dreams, to listen to your inner voice, and to navigate the shadows with courage and curiosity.",
    "reversedMeaning": "Confusion, illusion, and fear are clouding your judgment. The reversed Moon suggests you may be struggling to distinguish between reality and illusion. This is a moment to confront your fears and to seek clarity in the midst of uncertainty. Are you allowing your subconscious fears to dictate your actions? Healing requires facing your shadows and finding the truth within the chaos."
  },
  {
    "name": "Judgement",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/20.jpg",
    "meaning": "Awakening, rebirth, and a call to higher purpose are at hand. The Judgement card represents a moment of profound transformation, where you are being called to rise above past mistakes and embrace a new chapter in your life. This is a time of reflection, where you evaluate your past actions and make decisions that align with your higher self. Judgement encourages you to let go of old patterns and to step into your true purpose with clarity and conviction.",
    "reversedMeaning": "Self-doubt, fear of judgment, and resistance to change are holding you back. The reversed Judgement card suggests you may be struggling to let go of the past or to embrace the changes that are necessary for your growth. This is a moment to confront your fears and to trust in the process of transformation. Are you resisting the call to awaken to your true potential? Healing requires releasing old judgments and embracing the opportunity for renewal."
  },
  {
    "name": "The World",
    "image": "https://raw.githubusercontent.com/alnero/Zipline-data/master/Taro/img/21.jpg",
    "meaning": "Completion, fulfillment, and a sense of wholeness are within reach. The World represents the culmination of a long journey, where all the pieces of your life come together in harmony. This card signifies achievement, success, and the realization of your goals. It’s a time to celebrate your accomplishments and to recognize the growth you’ve experienced. The World encourages you to embrace the fullness of life and to step into your role as a co-creator of your destiny.",
    "reversedMeaning": "Lack of closure, unfinished business, and a sense of incompletion are lingering. The reversed World suggests you may be struggling to bring a chapter of your life to a close. This is a moment to reflect on what still needs to be addressed and to take the necessary steps to achieve closure. Are you holding onto something that no longer serves you? Healing requires letting go of the past and embracing the new opportunities that await."
  }
];

